const CLASSIFICATIONS = {
  precision: {
    label: "Precision",
    description: "Numerical accuracy, correctness guarantees, edge case handling",
    levels: ["Approximate", "Standard", "High", "Exact"],
  },
  robustness: {
    label: "Robustness",
    description: "Fault tolerance, error handling, recovery from invalid input",
    levels: ["Fragile", "Guarded", "Resilient", "Hardened"],
  },
  timeSpace: {
    label: "Time-Space",
    description: "Computational complexity and memory characteristics",
    levels: ["Compact", "Balanced", "Speed-opt", "Memory-opt"],
  },
  sizeLimits: {
    label: "Size Limits",
    description: "Scale of data the component handles effectively",
    levels: ["Tiny", "Medium", "Large", "Unbounded"],
  },
  bindingTime: {
    label: "Binding Time",
    description: "When parameters/configuration are resolved",
    levels: ["Compile", "Link", "Load", "Runtime"],
  },
};

const CATEGORIES = [
  "Parsing & Serialization",
  "Cryptography & Hashing",
  "Data Structures",
  "Concurrency & Async",
  "Networking & HTTP",
  "Text Processing",
  "Compression",
  "Date & Time",
  "Numerical Computation",
  "Logging & Observability",
];

const COMPONENTS = [
  // Parsing & Serialization
  {
    id: "serde",
    name: "serde",
    ecosystem: "Rust",
    category: "Parsing & Serialization",
    summary: "Generic serialization/deserialization framework with compile-time code generation. The de facto standard for data interchange in Rust.",
    classifications: { precision: 3, robustness: 3, timeSpace: 2, sizeLimits: 3, bindingTime: 0 },
    comparable: ["protobuf", "jackson"],
    notes: "Zero-copy deserialization available via serde_bytes/serde_json::RawValue. Format-agnostic: JSON, TOML, YAML, MessagePack, Bincode all plug in as interchangeable backends.",
    portability: "Rust (native). Conceptual equivalents in every major language but API not directly transliterable.",
    license: "MIT/Apache-2.0",
  },
  {
    id: "protobuf",
    name: "Protocol Buffers",
    ecosystem: "Multi",
    category: "Parsing & Serialization",
    summary: "Schema-driven binary serialization with cross-language code generation. Enforces structural contracts between services.",
    classifications: { precision: 3, robustness: 3, timeSpace: 2, sizeLimits: 3, bindingTime: 0 },
    comparable: ["serde", "flatbuffers", "capnproto"],
    notes: "Schema evolution via field numbering. Proto3 syntax simplified but loses required fields. gRPC builds atop this for RPC.",
    portability: "C++, Java, Python, Go, Rust, C#, JS, Ruby, PHP, Dart, Kotlin, Objective-C — generated from .proto IDL.",
    license: "BSD-3-Clause",
  },
  {
    id: "jackson",
    name: "Jackson",
    ecosystem: "Java",
    category: "Parsing & Serialization",
    summary: "High-performance JSON processor for Java. Streaming, tree-model, and data-binding APIs. Extensible to XML, YAML, CBOR, and more.",
    classifications: { precision: 2, robustness: 3, timeSpace: 1, sizeLimits: 3, bindingTime: 3 },
    comparable: ["serde", "gson"],
    notes: "Annotations control binding at compile time, but ObjectMapper configuration is fully runtime. Streaming API handles arbitrarily large documents.",
    portability: "JVM languages (Java, Kotlin, Scala, Clojure). Similar pattern in Gson (Java), System.Text.Json (.NET).",
    license: "Apache-2.0",
  },
  {
    id: "jq",
    name: "jq",
    ecosystem: "C / CLI",
    category: "Parsing & Serialization",
    summary: "Lightweight command-line JSON processor. A domain-specific language for transforming, filtering, and querying structured data.",
    classifications: { precision: 2, robustness: 2, timeSpace: 1, sizeLimits: 1, bindingTime: 3 },
    comparable: ["yq", "fx"],
    notes: "Streaming mode (--stream) handles large files but most use is in-memory. The filter language is Turing-complete. Bindings exist for many languages.",
    portability: "Any platform with a C compiler. Installable on all major OS. Language bindings: Python (jq.py), Go (gojq), Rust (jaq).",
    license: "MIT",
  },
  // Cryptography & Hashing
  {
    id: "libsodium",
    name: "libsodium",
    ecosystem: "C",
    category: "Cryptography & Hashing",
    summary: "Misuse-resistant cryptographic library. Provides authenticated encryption, key exchange, hashing, and signatures with safe defaults.",
    classifications: { precision: 3, robustness: 3, timeSpace: 2, sizeLimits: 2, bindingTime: 1 },
    comparable: ["openssl", "ring", "boringssl"],
    notes: "Designed to make incorrect usage difficult. Constant-time operations throughout. No algorithm negotiation — opinionated choices reduce attack surface.",
    portability: "C (native). Bindings: Python (PyNaCl), JS (libsodium.js/WASM), Rust (sodiumoxide), Go, PHP, .NET, Ruby, Erlang, Java.",
    license: "ISC",
  },
  {
    id: "ring",
    name: "ring",
    ecosystem: "Rust",
    category: "Cryptography & Hashing",
    summary: "Focused, correct, fast cryptographic operations. Fork of BoringSSL's crypto primitives, rewritten with Rust safety guarantees.",
    classifications: { precision: 3, robustness: 3, timeSpace: 2, sizeLimits: 2, bindingTime: 0 },
    comparable: ["libsodium", "openssl", "rustcrypto"],
    notes: "No unsafe-free claim but minimal unsafe usage, heavily audited. Backs rustls (TLS) and much of the Rust crypto ecosystem. FIPS not natively supported.",
    portability: "Rust (native). Used as backend for higher-level Rust crates. C ABI available but not primary interface.",
    license: "ISC-style",
  },
  {
    id: "openssl",
    name: "OpenSSL",
    ecosystem: "C",
    category: "Cryptography & Hashing",
    summary: "Comprehensive TLS and general-purpose cryptographic library. The most widely deployed crypto library in existence, for better and worse.",
    classifications: { precision: 3, robustness: 2, timeSpace: 1, sizeLimits: 3, bindingTime: 3 },
    comparable: ["libsodium", "ring", "boringssl", "libressl"],
    notes: "Vast algorithm support including legacy. FIPS 140-2/3 validated module available. Complex API surface leads to frequent misuse. LibreSSL and BoringSSL are hardened forks.",
    portability: "C (native). Bindings in virtually every language. Often the system-provided TLS on Linux. Windows/macOS have native alternatives (SChannel, SecureTransport).",
    license: "Apache-2.0 (3.x+)",
  },
  // Data Structures
  {
    id: "collections-rust",
    name: "std::collections",
    ecosystem: "Rust",
    category: "Data Structures",
    summary: "Standard library collections: HashMap, BTreeMap, VecDeque, BinaryHeap, HashSet, BTreeSet, LinkedList. Ownership-aware, zero-cost abstractions.",
    classifications: { precision: 3, robustness: 3, timeSpace: 2, sizeLimits: 2, bindingTime: 0 },
    comparable: ["java-collections", "cpp-stl"],
    notes: "HashMap uses SipHash (DoS-resistant) by default; swap hasher for performance. BTreeMap gives ordered iteration. No concurrent collections in std — see dashmap, crossbeam.",
    portability: "Rust (native). Conceptual equivalents universal. Trait-based generics enable uniform interface across types.",
    license: "MIT/Apache-2.0",
  },
  {
    id: "java-collections",
    name: "java.util.Collections",
    ecosystem: "Java",
    category: "Data Structures",
    summary: "The Collections Framework: List, Set, Map, Queue hierarchies with multiple implementations offering different time-space tradeoffs per interface.",
    classifications: { precision: 2, robustness: 3, timeSpace: 2, sizeLimits: 2, bindingTime: 3 },
    comparable: ["collections-rust", "cpp-stl"],
    notes: "Interface-driven: swap ArrayList↔LinkedList, HashMap↔TreeMap without changing calling code. ConcurrentHashMap and CopyOnWriteArrayList for thread-safe variants. This is closest to McIlroy's interchangeability vision.",
    portability: "JVM (native). The interface/implementation split is the archetype other ecosystems emulate.",
    license: "GPL-2.0-CE",
  },
  {
    id: "immer",
    name: "Immer",
    ecosystem: "C++",
    category: "Data Structures",
    summary: "Persistent immutable data structures using structural sharing. Vectors, maps, sets, and flex-vectors with O(log₃₂ N) operations.",
    classifications: { precision: 3, robustness: 3, timeSpace: 3, sizeLimits: 2, bindingTime: 0 },
    comparable: ["collections-rust", "immutable-js"],
    notes: "Hash Array Mapped Tries (HAMT) underneath. Enables efficient undo/redo, transactional semantics, and safe concurrency without locks. Inspired by Clojure's persistent data structures.",
    portability: "C++17 (native). Conceptual ports: Immer.js (JavaScript), pyrsistent (Python). Architecture pattern ports widely.",
    license: "BSL-1.0",
  },
  // Concurrency & Async
  {
    id: "tokio",
    name: "Tokio",
    ecosystem: "Rust",
    category: "Concurrency & Async",
    summary: "Async runtime providing event-driven, non-blocking I/O. Work-stealing scheduler, timers, channels, synchronization primitives.",
    classifications: { precision: 2, robustness: 3, timeSpace: 2, sizeLimits: 3, bindingTime: 3 },
    comparable: ["asyncio", "netty", "libuv"],
    notes: "Multi-threaded by default; single-threaded runtime available. select! macro for multiplexing futures. Tower middleware ecosystem builds atop it. io_uring support via tokio-uring.",
    portability: "Rust (native). Pattern equivalent to libuv (C/Node), asyncio (Python), Netty (Java). Not directly transliterable but architecturally uniform.",
    license: "MIT",
  },
  {
    id: "asyncio",
    name: "asyncio",
    ecosystem: "Python",
    category: "Concurrency & Async",
    summary: "Standard library async I/O framework. Single-threaded event loop with coroutines, tasks, streams, and subprocess support.",
    classifications: { precision: 2, robustness: 2, timeSpace: 1, sizeLimits: 2, bindingTime: 3 },
    comparable: ["tokio", "netty", "libuv"],
    notes: "GIL limits true CPU parallelism — use ProcessPoolExecutor for CPU-bound work. uvloop drop-in replacement doubles throughput. Structured concurrency via TaskGroups (3.11+).",
    portability: "Python 3.4+ (native). Pattern translates to async/await in JS, Rust, C#, Kotlin. Single-threaded model similar to Node.js.",
    license: "PSF",
  },
  {
    id: "crossbeam",
    name: "Crossbeam",
    ecosystem: "Rust",
    category: "Concurrency & Async",
    summary: "Lock-free concurrent data structures and utilities. Epoch-based memory reclamation, scoped threads, channels, and atomic primitives.",
    classifications: { precision: 3, robustness: 3, timeSpace: 2, sizeLimits: 3, bindingTime: 0 },
    comparable: ["java-concurrent", "tbb"],
    notes: "crossbeam-channel is faster than std::sync::mpsc. Scoped threads enable borrowing stack data without Arc. Epoch GC avoids ABA problem in lock-free structures.",
    portability: "Rust (native). Concepts from Java's java.util.concurrent and Intel TBB. Lock-free patterns universal but implementation is language-specific.",
    license: "MIT/Apache-2.0",
  },
  // Networking & HTTP
  {
    id: "curl",
    name: "libcurl",
    ecosystem: "C",
    category: "Networking & HTTP",
    summary: "The ubiquitous transfer library. HTTP(S), FTP, SMTP, SCP, and dozens more protocols. Battle-tested over 25+ years.",
    classifications: { precision: 2, robustness: 3, timeSpace: 1, sizeLimits: 3, bindingTime: 3 },
    comparable: ["hyper", "requests", "httpx"],
    notes: "Multi interface for async/parallel transfers. Callback-driven streaming. Used as backend by countless higher-level HTTP clients. curl CLI is the universal debugging tool.",
    portability: "C (native). Bindings: Python (pycurl), Ruby, PHP (built-in), Perl, Java, Rust, Go, .NET — essentially every language.",
    license: "curl (MIT-like)",
  },
  {
    id: "hyper",
    name: "hyper",
    ecosystem: "Rust",
    category: "Networking & HTTP",
    summary: "Low-level HTTP/1 and HTTP/2 implementation. Correct, fast, and minimal — a building block for higher-level frameworks.",
    classifications: { precision: 3, robustness: 3, timeSpace: 2, sizeLimits: 3, bindingTime: 0 },
    comparable: ["curl", "h2o", "nghttp2"],
    notes: "Sans-io design separates protocol logic from I/O. Powers reqwest (client) and axum (server). HTTP/3 support in progress. Memory-safe alternative to C implementations.",
    portability: "Rust (native). C API available (hyper-capi) for FFI. Conceptual equivalent to nghttp2 (C), Netty HTTP (Java).",
    license: "MIT",
  },
  // Text Processing
  {
    id: "regex-rust",
    name: "regex (Rust)",
    ecosystem: "Rust",
    category: "Text Processing",
    summary: "Guaranteed linear-time regular expressions. No backtracking, no catastrophic performance. Unicode-aware by default.",
    classifications: { precision: 2, robustness: 3, timeSpace: 2, sizeLimits: 3, bindingTime: 3 },
    comparable: ["re2", "pcre2", "hyperscan"],
    notes: "Thompson NFA / DFA hybrid. No backreferences or lookaround — trades expressiveness for guaranteed O(n) matching. regex-automata exposes lower-level control.",
    portability: "Rust (native). Same guarantees as RE2 (C++/Go). PCRE2 is more expressive but vulnerable to ReDoS.",
    license: "MIT/Apache-2.0",
  },
  {
    id: "re2",
    name: "RE2",
    ecosystem: "C++",
    category: "Text Processing",
    summary: "Safe, efficient regular expression library guaranteeing linear-time execution. Designed to be a drop-in replacement where PCRE is unsafe.",
    classifications: { precision: 2, robustness: 3, timeSpace: 2, sizeLimits: 3, bindingTime: 3 },
    comparable: ["regex-rust", "pcre2"],
    notes: "Created at Google after ReDoS incidents. Memory-bounded DFA caching. Go's regexp package uses the same algorithm. Missing features: backreferences, lookahead/lookbehind.",
    portability: "C++ (native). Bindings: Python (google-re2), Ruby, Node.js, Perl. Go regexp is a spiritual port.",
    license: "BSD-3-Clause",
  },
  {
    id: "icu",
    name: "ICU",
    ecosystem: "C / Java",
    category: "Text Processing",
    summary: "International Components for Unicode. Full Unicode support: normalization, collation, transliteration, date/number formatting, break iteration.",
    classifications: { precision: 3, robustness: 3, timeSpace: 1, sizeLimits: 2, bindingTime: 3 },
    comparable: ["ucd", "icu4x"],
    notes: "The authoritative Unicode implementation. Large binary size (~30MB data). ICU4X is the Rust rewrite targeting embedded/WASM with smaller footprint. CLDR locale data included.",
    portability: "C and Java (native dual implementation). Used by: Chrome, Node.js, Android, macOS, Windows. ICU4X targets Rust/WASM/FFI.",
    license: "Unicode-3.0",
  },
  // Compression
  {
    id: "zstd",
    name: "Zstandard (zstd)",
    ecosystem: "C",
    category: "Compression",
    summary: "Fast real-time compression algorithm. Configurable compression levels from ultra-fast to high-ratio. Dictionary compression for small data.",
    classifications: { precision: 3, robustness: 3, timeSpace: 2, sizeLimits: 3, bindingTime: 3 },
    comparable: ["lz4", "zlib", "brotli"],
    notes: "Level 1-3: faster than zlib at better ratios. Level 19-22: approaches LZMA ratios. Dictionary training for small messages (e.g., JSON logs). Seekable format for random access.",
    portability: "C (native). Bindings: Python, Rust, Java, Go, JS, .NET, Ruby. Supported in: HTTP (Content-Encoding), tar, btrfs, ZFS.",
    license: "BSD-3-Clause",
  },
  {
    id: "lz4",
    name: "LZ4",
    ecosystem: "C",
    category: "Compression",
    summary: "Extremely fast compression/decompression. Designed for speed over ratio — decompresses at multiple GB/s on modern hardware.",
    classifications: { precision: 2, robustness: 3, timeSpace: 2, sizeLimits: 3, bindingTime: 1 },
    comparable: ["zstd", "snappy"],
    notes: "LZ4 frame format for streaming. LZ4-HC variant trades speed for better compression. Used in: Linux kernel, ZFS, databases (ClickHouse, RocksDB), game engines.",
    portability: "C (native). Bindings in all major languages. Kernel-level support on Linux. Format is endian-neutral.",
    license: "BSD-2-Clause",
  },
  // Date & Time
  {
    id: "chrono",
    name: "chrono",
    ecosystem: "Rust",
    category: "Date & Time",
    summary: "Date and time library with timezone support, formatting, parsing, and arithmetic. Handles the full complexity of civil time.",
    classifications: { precision: 3, robustness: 2, timeSpace: 1, sizeLimits: 1, bindingTime: 3 },
    comparable: ["joda", "moment", "temporal"],
    notes: "NaiveDateTime (no TZ) vs DateTime<Tz> (TZ-aware) — type system prevents mixing. chrono-tz for IANA timezone database. jiff is a newer alternative with better ergonomics.",
    portability: "Rust (native). Pattern mirrors Joda-Time (Java) / java.time. JS Temporal proposal converging on similar API.",
    license: "MIT/Apache-2.0",
  },
  {
    id: "joda",
    name: "java.time (Joda successor)",
    ecosystem: "Java",
    category: "Date & Time",
    summary: "The JSR-310 date-time API. Immutable, thread-safe types for instants, durations, local/zoned times. Replaced the notoriously broken java.util.Date.",
    classifications: { precision: 3, robustness: 3, timeSpace: 1, sizeLimits: 1, bindingTime: 3 },
    comparable: ["chrono", "temporal", "arrow"],
    notes: "Distinct types: Instant, LocalDate, LocalTime, ZonedDateTime, Duration, Period — preventing category errors. The gold standard of date-time API design. Joda-Time is the predecessor.",
    portability: "JVM (native since Java 8). Backport: ThreeTen-Backport. Inspired: Rust chrono, JS Temporal, Python dateutil patterns.",
    license: "GPL-2.0-CE",
  },
  // Numerical Computation
  {
    id: "numpy",
    name: "NumPy",
    ecosystem: "Python",
    category: "Numerical Computation",
    summary: "N-dimensional array computation. Vectorized operations, broadcasting, linear algebra, FFT, random number generation. The foundation of scientific Python.",
    classifications: { precision: 2, robustness: 2, timeSpace: 2, sizeLimits: 2, bindingTime: 3 },
    comparable: ["ndarray", "eigen", "julia-arrays"],
    notes: "Float64 default; float32/float16 available. C-contiguous and Fortran-contiguous layouts. BLAS/LAPACK backend configurable (OpenBLAS, MKL). Buffer protocol enables zero-copy interop.",
    portability: "Python (native). WASM build available (Pyodide). Conceptual equivalent: ndarray (Rust), Eigen (C++), Julia's built-in arrays.",
    license: "BSD-3-Clause",
  },
  {
    id: "eigen",
    name: "Eigen",
    ecosystem: "C++",
    category: "Numerical Computation",
    summary: "Header-only template library for linear algebra. Matrices, vectors, solvers, and geometry with expression template optimization.",
    classifications: { precision: 3, robustness: 2, timeSpace: 2, sizeLimits: 2, bindingTime: 0 },
    comparable: ["numpy", "ndarray", "armadillo"],
    notes: "Compile-time size specialization: Matrix3d vs MatrixXd. Expression templates eliminate temporaries. SIMD auto-vectorization. Used in TensorFlow, ROS, Ceres Solver.",
    portability: "C++ (header-only, no dependencies). Compiles anywhere with C++14. No external BLAS required but can use one.",
    license: "MPL-2.0",
  },
  // Logging & Observability
  {
    id: "opentelemetry",
    name: "OpenTelemetry",
    ecosystem: "Multi",
    category: "Logging & Observability",
    summary: "Vendor-neutral observability framework. Unified API for traces, metrics, and logs. The CNCF standard for distributed telemetry.",
    classifications: { precision: 2, robustness: 2, timeSpace: 1, sizeLimits: 3, bindingTime: 3 },
    comparable: ["tracing-rust", "prometheus", "zipkin"],
    notes: "SDK + Collector architecture. Exporters swap backends without code changes (Jaeger, Prometheus, Datadog, etc). Context propagation across service boundaries. Sampling controls cost.",
    portability: "Go, Java, Python, JS, .NET, Rust, C++, Ruby, PHP, Erlang, Swift — first-party SDKs. Protocol (OTLP) is the interop layer.",
    license: "Apache-2.0",
  },
  {
    id: "tracing-rust",
    name: "tracing",
    ecosystem: "Rust",
    category: "Logging & Observability",
    summary: "Structured, contextual, async-aware instrumentation. Spans and events with typed fields. Subscriber architecture for pluggable backends.",
    classifications: { precision: 2, robustness: 3, timeSpace: 2, sizeLimits: 2, bindingTime: 0 },
    comparable: ["opentelemetry", "slog", "log4j"],
    notes: "Spans carry context across await points — essential for async Rust. tracing-subscriber for formatting/filtering. tracing-opentelemetry bridges to OTel. Compile-time level filtering via features.",
    portability: "Rust (native). Conceptual equivalent to structured logging in any language. Bridges to OpenTelemetry for cross-language interop.",
    license: "MIT",
  },
];

export const data = {
  CLASSIFICATIONS,
  CATEGORIES,
  COMPONENTS
};
